# Generated by Django 4.0.4 on 2022-05-30 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loan', '0001_initial'),
        ('extra', '0001_initial'),
        ('book', '0001_initial'),
        ('accounting', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(to='extra.category'),
        ),
        migrations.AddField(
            model_name='book',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.loan'),
        ),
        migrations.AddField(
            model_name='book',
            name='poblisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='extra.publisher'),
        ),
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.customuser'),
        ),
    ]
