# Generated by Django 4.0.4 on 2022-05-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('phone_number', models.CharField(max_length=11)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Famale')], max_length=20)),
                ('addres', models.TextField()),
                ('nationalcode', models.CharField(max_length=10)),
            ],
        ),
    ]
